FROM nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04

RUN apt-get update &&\
    apt-get -y install build-essential yasm nasm unzip wget sysstat tmux python-setuptools libtcmalloc-minimal4 git pkgconf

RUN git clone -b sdk/8.1 --single-branch https://git.videolan.org/git/ffmpeg/nv-codec-headers.git &&\
    cd nv-codec-headers && make install && cd ..

RUN git clone --depth 1 -b release/4.0 --single-branch https://github.com/FFmpeg/FFmpeg.git &&\
    cd FFmpeg &&\
    mkdir ffmpeg_build && cd ffmpeg_build &&\
    ../configure \
    --enable-cuda \
    --enable-cuvid \
    --enable-shared \
    --disable-static \
    --disable-programs \
    --disable-doc \
    --extra-cflags=-I/usr/local/cuda/include \
    --extra-ldflags=-L/usr/local/cuda/lib64 \
    --enable-gpl \
    --extra-libs=-lpthread \
    --nvccflags="-gencode arch=compute_75,code=sm_75 -O3" &&\
    make -j$(nproc) && make install && ldconfig

RUN apt-get -y remove cmake
RUN git clone https://github.com/Kitware/CMake.git && \
    cd CMake && ./bootstrap && make && make install

RUN apt-get -y install autoconf libtool python3 python3-pip python3-dev build-essential python3-setuptools

RUN apt-get -y remove protobuf-compiler
RUN git clone https://github.com/protocolbuffers/protobuf.git && \
    cd protobuf && git submodule update --init --recursive && \
    ./autogen.sh

RUN pip3 install twine
RUN pip3 install awscli

RUN cd /tmp &&\
    git clone https://github.com/doxygen/doxygen.git &&\
    cd doxygen &&\
    git checkout dc89ac0 &&\
    mkdir build &&\
    cd build &&\
    apt-get update &&\
    apt-get install -y flex bison &&\
    cmake -G "Unix Makefiles" .. &&\
    make install &&\
    cd / &&\
    rm -rf /tmp/doxygen

# Install pytorch
RUN pip3 install numpy torchvision_nightly
RUN pip3 install torch_nightly -f https://download.pytorch.org/whl/nightly/cu100/torch_nightly.html

COPY . /app
WORKDIR /app

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES video,compute,utility
